kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: quobyte-dyn
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: quobyte-dynamic-tenant 
