kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: quobyte-default-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: quobyte-default
