allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: quobyte-dynamic-tenant
reclaimPolicy: Delete
parameters:
  accessMode: "770"
  createQuota: "true"
  csi.storage.k8s.io/controller-expand-secret-name: quobyte-secret
  csi.storage.k8s.io/controller-expand-secret-namespace: ${pvc.namespace}
  csi.storage.k8s.io/provisioner-secret-name: quobyte-secret
  csi.storage.k8s.io/provisioner-secret-namespace: ${pvc.namespace}
  csi.storage.k8s.io/node-publish-secret-name: quobyte-secret
  csi.storage.k8s.io/node-publish-secret-namespace: ${pvc.namespace}
  group: root
  quobyteConfig: BASE
  user: root
  labels: "mediatype:hdd"
provisioner: csi.quobyte.com

